### ISSUE TITLE
refactor: do plugin universal css agnostic

### ISSUE THREAD

**Issue by reslear** [ofcold/security-code#10]
hi @lilianjin, i'm suggest do plugin css agnostic: 

- [ ] remove tailwind classes from plugin
- [ ] add specific plugin classes like (sc-container, sc-wrapper, sc-input etc...)
- [ ] add styles to `.css` for vanilla css (compiled with tailwind)  and importing if need [1]
- [x] add to `package.json` separate exports for css files 
- [ ] add instruction how to use with tailwind and well-now classes with `@apply` syntax [2]
- [x] rewrite to typescript

[1]
```js
// importing styles if need css 
import 'ofcold-security-code/styles.css'
```
```css
.sc-container {
   display:flex;
   margin-left: auto;
   margin-right: auto;
}
```

[2]
```css
.sc-container {
   @apply flex flex-direction ml-auto mr-auto
}
```
